- name: Install Nginx
  apt: name={{ item }} state=present
  with_items:
   - nginx
   - nginx-extras

- name: Configure Nginx
  template: src=nginx.conf.template dest=/etc/nginx/nginx.conf

- name: Configure site-available/default
  template: src=default.template dest=/etc/nginx/sites-available/default
  notify: restart nginx
